### ISSUE TITLE
Optimize image files

### ISSUE THREAD

**Issue by NewsGuyTor** [Tapiosinn/tv-logos#3]
I noticed your icons are unoptimized PNGs, you could save quite a bit of space (thereby making them load faster in playlists) by optimizing them with tools like ImageOptim. 

I tried optimizing the New Zealand folder and was able to reduce the file size by 35% on average losslessly.

![Skjermbilde 2020-06-08 kl  14 09 02](https://user-images.githubusercontent.com/19603024/84028849-bc233f00-a991-11ea-8fa8-c75d191e4433.png)

**Comment by Tapiosinn** [comment]
Hi! Thanks for letting me know, I did early on try out some optimisation, mostly in Photoshop but the quality of the logos got so bad when I tried it. Since I'm using png's and svg's are currently not supported everywhere, I noticed that when I did my optimisation the edges of the png's became very bad and looked terrible on screen. I think the recent logos are smaller as I'm using more compression in Photoshop, but maybe that does nothing.

I've also noticed that png's exported from Illustrator are only ~30-40% of the size compared to exporting from Photoshop. But I'll see if I can try this tool or tweak my settings and get better results. I have for the past month or so being doing some test to reduce file size and I'm thinking about making a 512px or 320px logos in a separate folder. Although this just started as a personal project, not everyone wants large logos.

For example I've now for a few days be re-creating from scratch all the beIN Sports logos, and boy they are many. It's the version hard to get, the same as on-screen-bug, with the gradient. And I export them directly from Illustrator and they are 1024px width and ~25KB, I think thats good. The stacked version's with no gradient are around ~5KB. 

But thanks for your input, I really appreciate it :)

**Comment by NewsGuyTor** [comment]
Separate good lossless optimization tools like ImageOptim works quite differently from what you are talking about in Photoshop/Illustrator. The key word is lossless, there's no quality change at all. The only trade-off is the time optimizing takes initially, even small images can take a minute to optimize.

If you want I can batch resize all icons and then optimize them overnight.

**Comment by Tapiosinn** [comment]
Hi. I try to have all the logos in min&max 1024px width. I changed the folder structure in the nordic folder and created folder for each country. If you want to add logos for Norway just make sure they are 1024px png's and are visible on a dark background and follow the naming convention.
